/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoAPP;

import View.MainScreen;

public class App {
    
    public static void main(String[] args) {
        
        MainScreen e = new MainScreen();
        e.setVisible(true);
        e.setLocationRelativeTo(null);
    }

    Object getGreeting() {
    return "Hello World!";
}

}
