/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Project_Controller;
import Controller.Task_Controller;
import Model.Project;
import Model.Task;
import Util.DeadLineColor;
import Util.EditButton;
import Util.TaskTableModel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class MainScreen extends javax.swing.JFrame {

    
    Project_Controller projectController;
    Task_Controller taskController;
    
    DefaultListModel projectsModel;
    TaskTableModel taskModel;
    
    public MainScreen() {
        try
        {
            initComponents();
            InitDataController(); 
            InitComponentModel();
            DecorateTableTask(); 
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPanel_Task = new javax.swing.JScrollPane();
        Task_TableTasks = new javax.swing.JTable();
        Panel_ToolBar = new javax.swing.JPanel();
        ToolBar_Title = new javax.swing.JLabel();
        ToolBar_SubTitle = new javax.swing.JLabel();
        Panel_Projects = new javax.swing.JPanel();
        Projects_Title = new javax.swing.JLabel();
        Projects_AddProject = new javax.swing.JLabel();
        Panel_Tasks = new javax.swing.JPanel();
        Tasks_Title = new javax.swing.JLabel();
        Tasks_AddTask = new javax.swing.JLabel();
        Panel_ProjectList = new javax.swing.JPanel();
        ProjectList_Project = new javax.swing.JScrollPane();
        Project_Lists = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        Panel_EmptyList = new javax.swing.JPanel();
        EmptyList_Icon = new javax.swing.JLabel();
        EmptyList_Title = new javax.swing.JLabel();
        EmptyList_SubTitle = new javax.swing.JLabel();

        Task_TableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Task_TableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Tarefa Concluída"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Task_TableTasks.setGridColor(new java.awt.Color(255, 255, 255));
        Task_TableTasks.setRowHeight(40);
        Task_TableTasks.setSelectionBackground(new java.awt.Color(204, 255, 204));
        Task_TableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Task_TableTasks.setShowHorizontalLines(true);
        Task_TableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Task_TableTasksMouseClicked(evt);
            }
        });
        ScrollPanel_Task.setViewportView(Task_TableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(660, 700));

        Panel_ToolBar.setBackground(new java.awt.Color(0, 153, 102));

        ToolBar_Title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ToolBar_Title.setForeground(new java.awt.Color(255, 255, 255));
        ToolBar_Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Check_3.png"))); // NOI18N
        ToolBar_Title.setText(" Centro de Tarefas App");

        ToolBar_SubTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ToolBar_SubTitle.setForeground(new java.awt.Color(255, 255, 255));
        ToolBar_SubTitle.setText("Anote tudo, não esqueça de nada");

        javax.swing.GroupLayout Panel_ToolBarLayout = new javax.swing.GroupLayout(Panel_ToolBar);
        Panel_ToolBar.setLayout(Panel_ToolBarLayout);
        Panel_ToolBarLayout.setHorizontalGroup(
            Panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToolBar_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToolBar_SubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_ToolBarLayout.setVerticalGroup(
            Panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolBarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(ToolBar_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToolBar_SubTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_Projects.setBackground(java.awt.Color.white);
        Panel_Projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Projects_Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Projects_Title.setForeground(new java.awt.Color(0, 153, 102));
        Projects_Title.setText("Projetos");

        Projects_AddProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_2.png"))); // NOI18N
        Projects_AddProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Projects_AddProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ProjectsLayout = new javax.swing.GroupLayout(Panel_Projects);
        Panel_Projects.setLayout(Panel_ProjectsLayout);
        Panel_ProjectsLayout.setHorizontalGroup(
            Panel_ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Projects_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Projects_AddProject))
        );
        Panel_ProjectsLayout.setVerticalGroup(
            Panel_ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Projects_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Projects_AddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Panel_Tasks.setBackground(java.awt.Color.white);
        Panel_Tasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Tasks_Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Tasks_Title.setForeground(new java.awt.Color(0, 153, 102));
        Tasks_Title.setText("Tarefas");

        Tasks_AddTask.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_2.png"))); // NOI18N
        Tasks_AddTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tasks_AddTaskMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_TasksLayout = new javax.swing.GroupLayout(Panel_Tasks);
        Panel_Tasks.setLayout(Panel_TasksLayout);
        Panel_TasksLayout.setHorizontalGroup(
            Panel_TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tasks_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tasks_AddTask))
        );
        Panel_TasksLayout.setVerticalGroup(
            Panel_TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tasks_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Tasks_AddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Panel_ProjectList.setBackground(java.awt.Color.white);
        Panel_ProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Panel_ProjectList.setToolTipText("");

        Project_Lists.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        Project_Lists.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Project_Lists.setFixedCellHeight(50);
        Project_Lists.setSelectionBackground(new java.awt.Color(0, 153, 102));
        Project_Lists.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Project_ListsMouseClicked(evt);
            }
        });
        ProjectList_Project.setViewportView(Project_Lists);

        javax.swing.GroupLayout Panel_ProjectListLayout = new javax.swing.GroupLayout(Panel_ProjectList);
        Panel_ProjectList.setLayout(Panel_ProjectListLayout);
        Panel_ProjectListLayout.setHorizontalGroup(
            Panel_ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectList_Project)
                .addContainerGap())
        );
        Panel_ProjectListLayout.setVerticalGroup(
            Panel_ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectList_Project)
                .addContainerGap())
        );

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        Panel_EmptyList.setBackground(java.awt.Color.white);

        EmptyList_Icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyList_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lists.png"))); // NOI18N

        EmptyList_Title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmptyList_Title.setForeground(new java.awt.Color(0, 153, 102));
        EmptyList_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyList_Title.setText("Nenhuma Tarefa por aqui :D");

        EmptyList_SubTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmptyList_SubTitle.setForeground(new java.awt.Color(153, 153, 153));
        EmptyList_SubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyList_SubTitle.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout Panel_EmptyListLayout = new javax.swing.GroupLayout(Panel_EmptyList);
        Panel_EmptyList.setLayout(Panel_EmptyListLayout);
        Panel_EmptyListLayout.setHorizontalGroup(
            Panel_EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EmptyListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmptyList_Icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmptyList_SubTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addComponent(EmptyList_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_EmptyListLayout.setVerticalGroup(
            Panel_EmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_EmptyListLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(EmptyList_Icon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmptyList_Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmptyList_SubTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(Panel_EmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_Projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Panel_Tasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Projects_AddProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Projects_AddProjectMouseClicked
        ProjectDialogScreen projectDialog =  new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialog.setLocationRelativeTo(null);
        projectDialog.setVisible(true);
        
        
        projectDialog.addWindowListener(new WindowAdapter()
        {
            public void windowClosed(WindowEvent e)
            {
                LoadProjects();
                if (!projectsModel.isEmpty()) 
                {
                    Project_Lists.setSelectedIndex(Project_Lists.getLastVisibleIndex());
                }
            }
        });
    }//GEN-LAST:event_Projects_AddProjectMouseClicked

    private void Tasks_AddTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tasks_AddTaskMouseClicked
        
        if(projectsModel.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Por favor crie um projeto");
            return;
        }
        TaskDialogScreen dialog = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        int projectIndex = Project_Lists.getSelectedIndex();
        Project project = (Project)projectsModel.get(projectIndex);
        
        dialog.setProject(project);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
        dialog.addWindowListener(new WindowAdapter()
        {
            public void windowClosed(WindowEvent e)
            {
                int projectIndex = Project_Lists.getSelectedIndex();
                Project project = (Project)projectsModel.get(projectIndex);
                LoadTasks(project.getId());
            }
        });
    }//GEN-LAST:event_Tasks_AddTaskMouseClicked

    private void Task_TableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Task_TableTasksMouseClicked
        int rowIndex = Task_TableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = Task_TableTasks.columnAtPoint(evt.getPoint());
        Task task = taskModel.getTasks().get(rowIndex);
        int projectIndex = Project_Lists.getSelectedIndex();
        Project project = (Project)projectsModel.get(projectIndex);
        switch(columnIndex)
        {
            case 3:
                taskController.Update(task);
                
                break;
            case 4:
                TaskDialogScreen_Update update = new TaskDialogScreen_Update(this,rootPaneCheckingEnabled);
                update.setProject(project);
                update.GetValuesProject(task);
                update.setLocationRelativeTo(null);
                update.setVisible(true);
                update.addWindowListener(new WindowAdapter()
                {
                    public void windowClosed(WindowEvent e)
                    {
                        int projectIndex = Project_Lists.getSelectedIndex();
                        Project project = (Project)projectsModel.get(projectIndex);
                        update.AtualizarDados(task);
                        taskController.Update(task);
                        LoadTasks(project.getId());
                    }
                });
                break;

            case 5:
                int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir a tarefa?", 
                        "Confirmação", JOptionPane.YES_NO_OPTION);
                if(resposta == JOptionPane.YES_OPTION)
                {
                    taskController.RemoveById(task.getId());
                    taskModel.getTasks().remove(task);
                }
                else
                {
                    return;
                }
                LoadTasks(project.getId());
                break;
        }
        
    }//GEN-LAST:event_Task_TableTasksMouseClicked

    private void Project_ListsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Project_ListsMouseClicked
        int projectIndex = Project_Lists.getSelectedIndex();
        Project project = (Project)projectsModel.get(projectIndex);
        LoadTasks(project.getId());
        if(SwingUtilities.isRightMouseButton(evt))
        {
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o projeto selecionado?\n                       '" +project.getName() + "'", 
                        "Confirmação", JOptionPane.YES_NO_OPTION);
            if(resposta == JOptionPane.YES_OPTION)
            {
                projectController.RemoveById(project.getId());
                JOptionPane.showMessageDialog(rootPane, "Projeto excluído com sucesso");
            }
            else
            {
                return;
            }
            LoadProjects();
        }
    }//GEN-LAST:event_Project_ListsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmptyList_Icon;
    private javax.swing.JLabel EmptyList_SubTitle;
    private javax.swing.JLabel EmptyList_Title;
    private javax.swing.JPanel Panel_EmptyList;
    private javax.swing.JPanel Panel_ProjectList;
    private javax.swing.JPanel Panel_Projects;
    private javax.swing.JPanel Panel_Tasks;
    private javax.swing.JPanel Panel_ToolBar;
    private javax.swing.JScrollPane ProjectList_Project;
    private javax.swing.JList<String> Project_Lists;
    private javax.swing.JLabel Projects_AddProject;
    private javax.swing.JLabel Projects_Title;
    private javax.swing.JScrollPane ScrollPanel_Task;
    private javax.swing.JTable Task_TableTasks;
    private javax.swing.JLabel Tasks_AddTask;
    private javax.swing.JLabel Tasks_Title;
    private javax.swing.JLabel ToolBar_SubTitle;
    private javax.swing.JLabel ToolBar_Title;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
    
    
    public void DecorateTableTask()
    {
        Task_TableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        Task_TableTasks.getTableHeader().setBackground(new Color(0,153,102));
        Task_TableTasks.getTableHeader().setForeground(new Color(255,255,255));
        
        
        //Task_TableTasks.setAutoCreateRowSorter(true);
        
    }
    
    public void InitDataController()
    {
        projectController = new Project_Controller();
        taskController = new Task_Controller();
    }
    
    public void InitComponentModel()
    {
        projectsModel = new DefaultListModel();
        LoadProjects();
        
        taskModel = new TaskTableModel();
        
        Task_TableTasks.setModel(taskModel);
        Task_TableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadLineColor());
        Task_TableTasks.getColumnModel().getColumn(4).setCellRenderer(new EditButton("Edit"));
        Task_TableTasks.getColumnModel().getColumn(5).setCellRenderer(new EditButton("Delete"));

        if (!projectsModel.isEmpty()) {
            Project_Lists.setSelectedIndex(0);
            int projectIndex = Project_Lists.getSelectedIndex();
            Project project = (Project) projectsModel.get(projectIndex);
            LoadTasks(project.getId());
        }
    }
    
    public void LoadTasks(int id)
    {
        List<Task> task = taskController.GetAll(id);
        taskModel.setTasks(task);
        ShowTableTasks(!task.isEmpty());
    }
    
    public void LoadProjects()
    {
        List<Project> projects = projectController.GetAll();
        projectsModel.clear();
        if(projects.isEmpty())
        {
            ShowTableTasks(false);
            return;
        }
        for(int x = 0; x < projects.size(); x++)
        {
            Project project = projects.get(x);
            projectsModel.addElement(project);
        }
        Project_Lists.setModel(projectsModel);
    }
    
    private void ShowTableTasks(boolean hasTasks)
    {
        if(hasTasks)
        {
            if(Panel_EmptyList.isVisible())
            {
                Panel_EmptyList.setVisible(false);
                jPanel5.remove(Panel_EmptyList);
            }
            jPanel5.add(ScrollPanel_Task);
            ScrollPanel_Task.setVisible(true);
            ScrollPanel_Task.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        }
        else
        {
            if(ScrollPanel_Task.isVisible())
            {
                ScrollPanel_Task.setVisible(false);
                jPanel5.remove(ScrollPanel_Task);
            }
            jPanel5.add(Panel_EmptyList);
            Panel_EmptyList.setVisible(true);
            Panel_EmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        }
    }

}

