/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.Project_Controller;
import Model.Project;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ProjectDialogScreen extends javax.swing.JDialog {

    Project_Controller controller;
    
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        controller = new Project_Controller();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_ToolBar = new javax.swing.JPanel();
        ToolBar_Title = new javax.swing.JLabel();
        ToolBar_IconSave = new javax.swing.JLabel();
        Panel_Project = new javax.swing.JPanel();
        Project_Name = new javax.swing.JLabel();
        Project_TextName = new javax.swing.JTextField();
        Project_Description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Project_TextDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(400, 300));

        Panel_ToolBar.setBackground(new java.awt.Color(0, 153, 102));

        ToolBar_Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ToolBar_Title.setForeground(new java.awt.Color(255, 255, 255));
        ToolBar_Title.setText("Projeto");

        ToolBar_IconSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToolBar_IconSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Check_WithoutBack.png"))); // NOI18N
        ToolBar_IconSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToolBar_IconSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ToolBarLayout = new javax.swing.GroupLayout(Panel_ToolBar);
        Panel_ToolBar.setLayout(Panel_ToolBarLayout);
        Panel_ToolBarLayout.setHorizontalGroup(
            Panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBar_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToolBar_IconSave)
                .addContainerGap())
        );
        Panel_ToolBarLayout.setVerticalGroup(
            Panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBar_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ToolBar_IconSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Panel_Project.setBackground(java.awt.Color.white);

        Project_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Project_Name.setText("Nome*");

        Project_TextName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Project_Description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Project_Description.setText("Descrição");

        Project_TextDescription.setColumns(20);
        Project_TextDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Project_TextDescription.setRows(5);
        jScrollPane1.setViewportView(Project_TextDescription);

        javax.swing.GroupLayout Panel_ProjectLayout = new javax.swing.GroupLayout(Panel_Project);
        Panel_Project.setLayout(Panel_ProjectLayout);
        Panel_ProjectLayout.setHorizontalGroup(
            Panel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(Project_Name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Project_TextName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Project_Description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_ProjectLayout.setVerticalGroup(
            Panel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Project_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Project_TextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Project_Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Panel_ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToolBar_IconSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolBar_IconSaveMouseClicked
        try
        {
            if(!Project_TextName.getText().trim().isEmpty())
            {
                Project project = new Project();
        
                project.setName(Project_TextName.getText());
                project.setDescription(Project_TextDescription.getText());
                controller.Save(project);
                JOptionPane.showMessageDialog(rootPane,"Projeto salvo com sucesso");
                
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Por favor insira um Nome*");
                Project_TextName.setText("");
                return;
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        
        dispose();
    }//GEN-LAST:event_ToolBar_IconSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Project;
    private javax.swing.JPanel Panel_ToolBar;
    private javax.swing.JLabel Project_Description;
    private javax.swing.JLabel Project_Name;
    private javax.swing.JTextArea Project_TextDescription;
    private javax.swing.JTextField Project_TextName;
    private javax.swing.JLabel ToolBar_IconSave;
    private javax.swing.JLabel ToolBar_Title;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
