/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.Task_Controller;
import Model.Project;
import Model.Task;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Usuario
 */
public class TaskDialogScreen extends javax.swing.JDialog {

    Task_Controller controller;
    Project project;
    public TaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new Task_Controller();
        try {
            MaskFormatter dateFormatter = new MaskFormatter("##/##/####");
            dateFormatter.setPlaceholderCharacter('_');
            Project_TextDeadLine.setFormatterFactory(new DefaultFormatterFactory(dateFormatter));
        } catch (ParseException e) {
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_ToolBar = new javax.swing.JPanel();
        ToolBar_Title = new javax.swing.JLabel();
        ToolBar_Save = new javax.swing.JLabel();
        Panel_Project = new javax.swing.JPanel();
        Project_Name = new javax.swing.JLabel();
        Project_TextName = new javax.swing.JTextField();
        Project_Description = new javax.swing.JLabel();
        Project_TextDescription = new javax.swing.JScrollPane();
        TextDescription_Text = new javax.swing.JTextArea();
        Project_DeadLine = new javax.swing.JLabel();
        Project_TextDeadLine = new javax.swing.JFormattedTextField();
        Project_Notes = new javax.swing.JLabel();
        Project_TextNotes = new javax.swing.JScrollPane();
        TextNotes_Text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 550));

        Panel_ToolBar.setBackground(new java.awt.Color(0, 153, 102));

        ToolBar_Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ToolBar_Title.setForeground(new java.awt.Color(255, 255, 255));
        ToolBar_Title.setText("Tarefa");

        ToolBar_Save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ToolBar_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Check_WithoutBack.png"))); // NOI18N
        ToolBar_Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ToolBar_SaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panel_ToolBarLayout = new javax.swing.GroupLayout(Panel_ToolBar);
        Panel_ToolBar.setLayout(Panel_ToolBarLayout);
        Panel_ToolBarLayout.setHorizontalGroup(
            Panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBar_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ToolBar_Save)
                .addContainerGap())
        );
        Panel_ToolBarLayout.setVerticalGroup(
            Panel_ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ToolBar_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ToolBar_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Panel_Project.setBackground(java.awt.Color.white);

        Project_Name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Project_Name.setText("Nome*");

        Project_TextName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Project_Description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Project_Description.setText("Descrição");

        TextDescription_Text.setColumns(20);
        TextDescription_Text.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextDescription_Text.setRows(5);
        Project_TextDescription.setViewportView(TextDescription_Text);

        Project_DeadLine.setText("Prazo*");

        Project_TextDeadLine.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        Project_Notes.setText("Notas");

        TextNotes_Text.setColumns(20);
        TextNotes_Text.setRows(5);
        Project_TextNotes.setViewportView(TextNotes_Text);

        javax.swing.GroupLayout Panel_ProjectLayout = new javax.swing.GroupLayout(Panel_Project);
        Panel_Project.setLayout(Panel_ProjectLayout);
        Panel_ProjectLayout.setHorizontalGroup(
            Panel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Project_TextNotes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Project_TextDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(Project_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Project_TextName)
                    .addComponent(Project_Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Project_DeadLine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Project_Notes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_ProjectLayout.createSequentialGroup()
                        .addComponent(Project_TextDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Panel_ProjectLayout.setVerticalGroup(
            Panel_ProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Project_Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Project_TextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Project_Description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Project_TextDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Project_DeadLine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Project_TextDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Project_Notes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Project_TextNotes, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Panel_ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_Project, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ToolBar_SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ToolBar_SaveMouseClicked
        try
        {
            if(!Project_TextName.getText().trim().isEmpty()&& Project_TextDeadLine.getText().replaceAll("[^0-9]", "").length() == 8)
            {
                Task task = new Task();
                task.setId_Project(project.getId());
                task.setName(Project_TextName.getText().trim());
                task.setDescription(TextDescription_Text.getText());
                task.setNotes(TextNotes_Text.getText());
            
            
                SimpleDateFormat simpleDate = new SimpleDateFormat("dd/MM/yyyy");
                Date deadLine = null;

                deadLine = simpleDate.parse(Project_TextDeadLine.getText());
                task.setDeadLine(deadLine);
                task.setCompleted(false);
                controller.Save(task);
            
                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso");
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Preencha os campos obrigatórios '*'");
                if(Project_TextName.getText().trim().isBlank())
                {
                    Project_TextName.setText("");
                }
                return;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        dispose();
    }//GEN-LAST:event_ToolBar_SaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogScreen dialog = new TaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Project;
    private javax.swing.JPanel Panel_ToolBar;
    private javax.swing.JLabel Project_DeadLine;
    private javax.swing.JLabel Project_Description;
    private javax.swing.JLabel Project_Name;
    private javax.swing.JLabel Project_Notes;
    private javax.swing.JFormattedTextField Project_TextDeadLine;
    private javax.swing.JScrollPane Project_TextDescription;
    private javax.swing.JTextField Project_TextName;
    private javax.swing.JScrollPane Project_TextNotes;
    private javax.swing.JTextArea TextDescription_Text;
    private javax.swing.JTextArea TextNotes_Text;
    private javax.swing.JLabel ToolBar_Save;
    private javax.swing.JLabel ToolBar_Title;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }


    
}
